bmusicalh/bmusicalh/Models/BandaMusic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace bmusicalh.Models
{
    public class BandaMusic
    {
        [Key]
        public int BandaMusicId { get; set; }

        [Display(Name = "Nombre")]
        public string BandaMusicName { get; set; }

        [Display(Name = "Genero")]
        public string BandaMusicGenero { get; set; }

        [Display(Name = "Pais")]
        public string BandaMusicCountry { get; set; }
    }
}

bmusicalh/bmusicalh/Models/ErrorViewModel.cs
using System;

namespace bmusicalh.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

bmusicalh/bmusicalh/Controllers/BandasMusicController.cs
using bmusicalh.Data;
using bmusicalh.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace bmusicalh.Controllers
{
    public class BandasMusicController : Controller
    {
        private readonly ApplicationDbContext db;

        public BandasMusicController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public async Task<IActionResult> Index()
        {
            return View(await db.BandasMusics.ToListAsync());

        }


        //crear por medio de vista

        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BandaMusic bandaMusic)
        {
            if (ModelState.IsValid)
            {
                db.Add(bandaMusic);
                await db.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(bandaMusic);
        }

        /////////////////////////////////////////////////////////////////////////////


        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depart = await db.BandasMusics.FirstOrDefaultAsync(d => d.BandaMusicId == id);
            if (depart == null)
            {
                return NotFound();
            }

            return View(depart);

        }

        //////////////////////////////////////////////////////////////////////////////

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depart = await db.BandasMusics.FindAsync(id);
            if (depart == null)
            {
                return NotFound();
            }

            return View(depart);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, BandaMusic banda)
        {
            if (id != banda.BandaMusicId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(banda);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return NotFound();

                }

                return RedirectToAction(nameof(Index));
            }

            return View(banda);
        }


        //////////////////////////////////////////////////////////////////////////
        ///

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var depart = await db.BandasMusics.FirstOrDefaultAsync(m => m.BandaMusicId == id);

            if (depart == null)
            {
                return NotFound();
            }

            return View(depart);

        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var depart = await db.BandasMusics.FindAsync(id);
            db.BandasMusics.Remove(depart);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


    }
}

bmusicalh/bmusicalh/Controllers/HomeController.cs
using bmusicalh.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace bmusicalh.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

bmusicalh/bmusicalh/Views/BandasMusic/Create.cshtml
@model bmusicalh.Models.BandaMusic

@{
    ViewData["Title"] = "Agregar Banda";

}

<h2>AGREGAR</h2>

<hr />

<div class="row" div>
    <div class="col-md-4">
        <form asp-action="Create">

            <div asp-validation-summary="ModelOnly" class="text-justify"></div>
            <div class="form-group">
                <label asp-for="BandaMusicName" class="control-label"></label>
                <input asp-for="BandaMusicName" class="form-control" />
                <span asp-validation-for="BandaMusicName" class="text-danger"></span>

                <label asp-for="BandaMusicGenero" class="control-label"></label>
                <input asp-for="BandaMusicGenero" class="form-control" />
                <span asp-validation-for="BandaMusicGenero" class="text-danger"></span>

                <label asp-for="BandaMusicCountry" class="control-label"></label>
                <input asp-for="BandaMusicCountry" class="form-control" />
                <span asp-validation-for="BandaMusicCountry" class="text-danger"></span>


                <br />
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-primary" />
                    <a asp-action="Index" class=" btn btn-warning">Regresar</a>
                </div>
            </div>
        </form>

    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

bmusicalh/bmusicalh/Views/BandasMusic/Delete.cshtml
@model bmusicalh.Models.BandaMusic

@{
    ViewData["Title"] = "Borrar";
}

<h1>Borrar</h1>
<h3>¿Esta seguro de eliminar este registro?</h3>

<div>
    <h4>Banda</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BandaMusicName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BandaMusicName)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BandaMusicGenero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BandaMusicGenero)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BandaMusicCountry)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BandaMusicCountry)
        </dd>
    </dl>
</div>
<br />
<div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="BandaMusicId" />
        <input type="submit" class="btn btn-danger" value="Borrar" />
        <a asp-action="Index" class="btn btn-success">Regresar</a>

    </form>
</div>

bmusicalh/bmusicalh/Views/BandasMusic/Details.cshtml
@model bmusicalh.Models.BandaMusic


@{
    ViewData["Title"] = "Details";


}

<h1>Detalles</h1>

<div>
    <h4>Departamento</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BandaMusicName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BandaMusicName)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BandaMusicGenero)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BandaMusicGenero)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BandaMusicCountry)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BandaMusicCountry)
        </dd>

    </dl>
</div>

<div>
    <a asp-action="Edit" class="btn btn-warning" asp-route-id="@Model.BandaMusicId">Editar</a>
    <a asp-action="Index" class=" btn btn-warning">Regresar</a>


</div>

bmusicalh/bmusicalh/Views/BandasMusic/Edit.cshtml
@model bmusicalh.Models.BandaMusic

@{
    ViewData["Title"] = "Editar Departamento";

}

<h2>Editar</h2>

<hr />

<div class="row" div>
    <div class="col-md-4">
        <form asp-action="Edit">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BandaMusicId" />
            <div class="form-group">
                <label asp-for="BandaMusicName" class="control-label"></label>
                <input asp-for="BandaMusicName" class="form-control" />
                <span asp-validation-for="BandaMusicName" class="text-danger"></span>

                <label asp-for="BandaMusicGenero" class="control-label"></label>
                <input asp-for="BandaMusicGenero" class="form-control" />
                <span asp-validation-for="BandaMusicGenero" class="text-danger"></span>

                <label asp-for="BandaMusicCountry" class="control-label"></label>
                <input asp-for="BandaMusicCountry" class="form-control" />
                <span asp-validation-for="BandaMusicCountry" class="text-danger"></span>

                <br />
                <div class="form-group">
                    <input type="submit" value="Editar" class="btn btn-primary" />
                    <a asp-action="Index" class=" btn btn-warning">Regresar</a>
                </div>
            </div>
        </form>

    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

bmusicalh/bmusicalh/Views/BandasMusic/Index.cshtml
@model  IEnumerable<bmusicalh.Models.BandaMusic>

    @{ 
        ViewData["Title"] = "Bandas Musicales";
    }

<H1>Bandas Musicales</H1>
<p>
    <a asp-action="Create" class="btn btn-dark">AGREGAR NUEVA</a>

    <table>
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BandaMusicName)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.BandaMusicName)</td>
                    <td>
                        <a asp-action="Edit" class="btn btn-warning" asp-route-id="@item.BandaMusicId">Editar</a>
                        <a asp-action="Details" class="btn btn-success" asp-route-id="@item.BandaMusicId">Detalles</a>
                        <a asp-action="Delete" class="btn btn-danger" asp-route-id="@item.BandaMusicId">Borrar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</p>

bmusicalh/bmusicalh/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

bmusicalh/bmusicalh/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bmusicalh</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">bmusicalh</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>



                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-controller="BandasMusic" asp-action="Index">Bandas</a>
                        </li>


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - bmusicalh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>